### ISSUE TITLE
謝謝你的心得與筆記

### ISSUE THREAD

**Issue by azole** [NhOuOiB/mfee27-nodejs-workshop#1]
我們在總共九天的課程當中，複習的比例可能會比你想像的還要多，不過，有時候我覺得是在複習，或有些同學覺得是複習的，對很多同學來說，可能是在學習新東西，我自己一直有一個想法是，知識與技能，至少在電腦科學與軟體開發這個領域，可以區分為基礎與應用，而且只要基礎穩固、扎實了，上層的應用就應該要有能力自學才對。

以前端來說，近幾年來新的框架、技術層出不窮，但說穿了，電腦科學發展至今，除去量子力學，基本上這幾十年來的基本架構沒有太大的變化，期待你們開始具有工程師的思維，其中一種就是，盡量不要去依賴別人教你，這不是說不用上課或是不需要跟同學討論，而是，你試著這樣想，作為軟體工程師，要學習的東西太多了，你必須要具備有「自學」的能力，我甚至認為，你在這個轉職的過程中，學再多種程式語言、技術、套件、框架，都遠不如，在這段時間，好好地找到屬於自己的、在這個領域學習的方式，以及打好電腦科學的基礎，因為語言、技術、套件是會過時的、是會被汰換的，唯有「學習的方法」及那些基礎不可動搖的。

所以，我會花很多的時間在幫你們打基礎，如果那些你學過了，那的確是複習沒錯，如果那些你還沒有很熟悉，那就跟著我們的課程去扎實地練下來。我不擔心上不完，因為在軟體開發的領域，本來就沒有學完的一天，所以一定上不完的啊 XD。

我希望經過這九天，你能有自己去學習的能力。當基礎穩固後，你會發現，再多的新東西，萬變不離其宗，當你能掌握根源，你才不會覺得每一樣都是「新」東西，才不會覺得很累、一直追追不完。當你能掌握其中的門道，很多東西，真的就只是應用而已，當然不是說發明這些應用的人不厲害，不，他們超強的，但我們作為使用的人，不該覺得那麼有負擔才是。

你也可以回想一下，我們在複習 git 的過程中，指令怎麼用的地方，我算是蠻快就帶過去了，但那些指令到底做了什麼事、背後的運作是什麼，如果我能知道的，我都會想要盡力去分享。指令怎麼用這個啊，說真的，你們去 google，一堆教學，自己看、多操作幾遍其實就可以了，但背後做了什麼事、下了指令後有什麼變化跟影響，分享的人就少了。不知道你會不會覺得，知道「為什麼」之後，會有一種比較「扎實」的感覺，好像比只知道怎麼用，覺得自己更會了一點點？說穿了，用起來都一樣，知不知道為什麼有差別嗎？我就是覺得有差，知道為什麼可以讓你們更有信心，更有把握說自己會了，也會更願意去探索，也更不害怕，當然距離完全不怕還有很長的距離，但信心是來自於底氣，底氣是來自於這些細微的累積。

總之，以上是我的理念，如果有覺得不合適的地方，歡迎隨時跟我討論，我是真的很希望，你們可以擁有在軟體工程師這條路上，必須要具備的自學能力！

**Comment by NhOuOiB** [comment]
我覺得老師說得非常有道理，在做小專的時候，因為跟小組的技術長還不錯，所以常常很多問題都沒有想很久，就直接問他，這讓我養成了壞習慣，周遭的工程師朋友也有說過**自學**很重要，接下來我想改掉這個不好的習慣，也想找到屬於自己的學習方法。

超級同意老師說的，會有大概知道用法，但不知道為什麼或是背後的原理是什麼，心裡就會有煩悶的感覺，說自己會用但卻不知道背後的原理，感覺就很心虛，我也覺得如果知道其原理，那應該就會應用。

這句話是金句，我會記下來的。
>但信心是來自於底氣，底氣是來自於這些細微的累積。


我相信應該也有一些同學跟我一樣，也很需要複習，就算是同樣的課程，我相信每次的複習都能學到新的東西，而且不同老師教的內容一定也不一樣。

最後，**非常感謝老師用心的回覆**，經由這段留言，能知道老師想教導我們的不只是知識，更多的是觀念、經驗還有人生方面的技能，能遇到這麼棒的老師真的太幸運了，老師如果你願意上到晚上9點，我相信大家都會很開心的 👍🏻 。
